shfmt pre-commit
Dasharo/dts-scripts pull request #36
Opened 2024-10-16 10:23 UTC by PLangowski

2024-10-16 10:28 UTC, PLangowski commented
I set the indent to 4 spaces, although I think 2 spaces also look okay.

2024-10-16 10:58 UTC, macpijan commented
> although I think 2 spaces also look okay.

Then we can try to go with 2 spaces, following https://google.github.io/styleguide/shellguide.html as well

2024-10-18 06:22 UTC, PLangowski commented
@macpijan done

2024-10-18 16:17 UTC, macpijan commented
Thanks, LGTM.

Would it be a problem for your UEFI capsule changes @DaniilKl if we merge this?
If so, we can hold off with merging.

2024-10-23 08:50 UTC, DaniilKl commented
@macpijan, yep, definitely there will be some rebasing, could you please merge it after QEMU/Capsule Update?

2024-10-23 09:09 UTC, macpijan commented
Sure, I guess we can run `shfmt` again after we merge capsule PR.

2024-12-05 09:35 UTC, m-iwanicki commented
@PLangowski QEMU/capsule update has been merged, are you going to rebase this PR?

2024-12-06 09:29 UTC, PLangowski commented
rebased

2024-12-06 09:49 UTC, m-iwanicki requested changes
Looks good. Not sure how much I like `>"$file"` as I always added space unless it's `2>&1` type redirect but otherwise I think it's great addition.

2024-12-06 09:49 UTC, m-iwanicki approved these changes
Wrong button I wanted to approve

2024-12-09 11:19 UTC, DaniilKl commented
> Can you check if this is fixable or maybe we should add suffix to all scripts?

If you add the suffix to all scripts - make sure to check everything that depends on the scripts and add suffixes there as well.

2024-12-09 11:22 UTC, m-iwanicki commented
@PLangowski Probably in Makefile. Install script without extension so we don't have to make changes in scripts

2025-02-14 09:44 UTC, m-iwanicki commented
@PLangowski Could you resolve requests (so all script files are checked) and rebase?

2025-02-17 07:34 UTC, PLangowski commented
Some problems appeared with shellcheck:

```
In scripts/dts.sh line 9:
source $DTS_SUBS
       ^-------^ SC1090 (warning): ShellCheck can't follow non-constant source. Use a directive to specify location.
```

I think we should ignore this warning instead of replacing the variables to full paths

2025-02-17 09:20 UTC, m-iwanicki commented
> Some problems appeared with shellcheck:

```
# shellcheck source=../include/dts-subscription.sh
```

2025-02-17 10:28 UTC, PLangowski commented
@m-iwanicki If everything is resolved, can you approve?

2025-02-17 13:29 UTC, m-iwanicki commented
@PLangowski not today, I'm busy for the whole day. I'll do more thorough review tomorrow.

2025-03-31 21:00 UTC, macpijan reviewed
no more comments from me as long as we can link to some results from executed tests, which should be required for such a tree-wide change

2025-04-15 13:48 UTC, PLangowski commented
@macpijan I ran the DTS test CI with scripts from this branch and they passed. https://github.com/Dasharo/meta-dts/actions/runs/14469896061/job/40582824146?pr=249
Is this enough?

2025-04-15 15:04 UTC, m-iwanicki approved these changes

2025-04-15 15:21 UTC, macpijan approved these changes

2025-04-15 15:21 UTC, merged