Enhance verbose mode
Dasharo/dts-scripts pull request #40
Opened 2024-10-31 14:38 UTC by PLangowski

2024-11-05 09:06 UTC, m-iwanicki requested changes
There are couple places where you don't pass `SHELLOPTS`, can you explain why or did you miss it?

* https://github.com/Dasharo/dts-scripts/blob/4b01ce1c81bf845815b9bc5379264f5b118bf712/scripts/dasharo-deploy#L846
* https://github.com/Dasharo/dts-scripts/blob/4b01ce1c81bf845815b9bc5379264f5b118bf712/reports/dasharo-hcl-report#L337
    *  Should probably remove https://github.com/Dasharo/dts-scripts/blob/4b01ce1c81bf845815b9bc5379264f5b118bf712/reports/dasharo-hcl-report#L53 as it's probably unneeded as we source `$DTS_FUNCS`
* https://github.com/Dasharo/dts-scripts/blob/4b01ce1c81bf845815b9bc5379264f5b118bf712/include/dts-functions.sh#L1529

2024-11-05 09:06 UTC, m-iwanicki commented on include/dts-functions.sh
> +          wait_for_network_connection &&  ${CMD_DASHARO_HCL_REPORT} && LOGS_SENT="1"
```suggestion
          wait_for_network_connection && ${CMD_DASHARO_HCL_REPORT} && LOGS_SENT="1"
```

2024-11-06 11:16 UTC, PLangowski commented on include/dts-functions.sh
> +          wait_for_network_connection &&  ${CMD_DASHARO_HCL_REPORT} && LOGS_SENT="1"
https://github.com/Dasharo/dts-scripts/compare/4b01ce1c81bf845815b9bc5379264f5b118bf712..8c3e02f5eefd1c7dab93864c64c75fd18e1d3704

2024-11-06 11:17 UTC, PLangowski commented on include/dts-functions.sh
> +      cp ${FLASHROM_LOG_FILE} $log_dir
What do you mean? It's added right above this.

2024-11-06 11:39 UTC, m-iwanicki commented on include/dts-functions.sh
> +      cp ${FLASHROM_LOG_FILE} $log_dir
You are right, not sure how I missed it.

2024-11-06 11:45 UTC, m-iwanicki approved these changes
Looks good, have you tested it?

2024-11-06 13:19 UTC, merged