dts-functions: add heads fw to V54x_6x_TU
Dasharo/dts-scripts pull request #49
Opened 2024-12-03 10:44 UTC by m-iwanicki

@mkopec Do I need to add `HEADS_SWITCH_FLASHROM_OPT_OVERRIDE="--ifd -i bios"`?
<https://docs.dasharo.com/unified/novacustom/firmware-transition/#switching-from-dasharo-uefi-to-heads> doesn't help as it just says to use DTS.

2024-12-05 09:44 UTC, PLangowski approved these changes
Looks good to me

2025-01-27 10:03 UTC, m-iwanicki commented
@PLangowski can you re-review? This PR will only add support for heads for V560TU.
Additionally when switching to heads we also have to update EC

2025-01-27 10:09 UTC, PLangowski approved these changes

2025-01-28 08:52 UTC, DaniilKl requested changes

2025-01-28 08:52 UTC, DaniilKl commented on include/dts-functions.sh
> +          HEADS_SWITCH_FLASHROM_OPT_OVERRIDE="--ifd -i bios"
You should add `HEADS_SWITCH_FLASHROM_OPT_OVERRIDE` only for `v560TU`.

2025-01-28 09:25 UTC, m-iwanicki commented on include/dts-functions.sh
> +          HEADS_SWITCH_FLASHROM_OPT_OVERRIDE="--ifd -i bios"
V540TU will also need it when we add heads release for it.

2025-01-28 09:27 UTC, m-iwanicki commented on include/dts-functions.sh
> +          HEADS_SWITCH_FLASHROM_OPT_OVERRIDE="--ifd -i bios"
https://github.com/Dasharo/dts-scripts/compare/537ce570f7939ff87902452dcf90bedffb7e2791..ba33b3f48150e066534dfe68605b6624e8b32a0e

2025-01-28 09:27 UTC, DaniilKl commented on include/dts-functions.sh
> +          HEADS_SWITCH_FLASHROM_OPT_OVERRIDE="--ifd -i bios"
But now only v560TU needs this variable, doesn't it?

2025-01-28 10:24 UTC, m-iwanicki commented on include/dts-functions.sh
> +          HEADS_SWITCH_FLASHROM_OPT_OVERRIDE="--ifd -i bios"
@DaniilKl I think you missed my commit by few seconds

2025-01-28 10:25 UTC, DaniilKl approved these changes

2025-01-28 11:04 UTC, merged