Use MinIO for DPP binaries
Dasharo/dts-scripts pull request #53
Opened 2024-12-12 10:31 UTC by PLangowski

2025-03-21 09:36 UTC, m-iwanicki requested changes
There are still couple leftovers:

```sh
$ grep -R "CLOUDSEND_PASSWORD\|CLOUDSEND_LOGS\|USER_DETAILS" -n
include/dts-environment.sh:31:BASE_CLOUDSEND_LOGS_URL="39d4biH4SkXD8Zm"
include/dts-environment.sh:32:BASE_CLOUDSEND_PASSWORD="1{\[\k6G"
include/dts-functions.sh:1153:    curl -sSfI -u "$USER_DETAILS" -H "$CLOUD_REQUEST" "$HEADS_LINK_DPP" -o /dev/null 2>>"$ERR_LOG_FILE"
include/dts-functions.sh:1700:    CLOUDSEND_PASSWORD=${DTS_LOGS_PASSWORD} cloudsend.sh \
scripts/cloud_list:28:USER_DETAILS="$CLOUDSEND_LOGS_URL:$CLOUDSEND_PASSWORD"
scripts/cloud_list:33:curl -L -f -u "$USER_DETAILS" -H "$CLOUD_REQUEST" -X PROPFIND "$tmpURL" -o "$TMP_RESPONSE" 2>>"$ERR_LOG_FILE"
scripts/cloud_list:56:curl -L -f -u "$USER_DETAILS" -H "$CLOUD_REQUEST" -X GET "$tmpURL" -o /$HCL_REPORT_NAME 2>>"$ERR_LOG_FILE"
```

One of those is sending console logs. There is also question of sending HCL reports (and console logs) when user isn't logged. You should probably create buckets for this on MinIO and hardcode password for this bucket in dts-scripts (as we are currently doing with cloud password for shared HCL report folder)

2025-03-21 09:36 UTC, m-iwanicki commented on include/dts-functions.sh
>  download_ec() {
```suggestion
download_ec() {
  echo "Downloading Dasharo EC firmware..."
```

2025-03-21 10:51 UTC, pietrushnic commented
@PLangowski how parsing and publishing results from HCL will work after transition to min.io: https://docs.dasharo.com/dev-proc/hcl-maintainer/

2025-03-21 10:53 UTC, m-iwanicki commented on reports/dasharo-hcl-report
>      if [ -a "${CMD_DASHARO_DEPLOY}" ]; then
```sh
echo -e "Something may be wrong with credentials. Please use option 4 to change DPP keys
               \rand make sure that there is no typo."
```

Maybe change this error message if it's possible to enter this part without DPP keys (normal HCL report without being logged in)?

2025-03-24 08:50 UTC, m-iwanicki requested changes

2025-03-24 08:50 UTC, m-iwanicki commented on include/dts-functions.sh
> +      fi
Does `login_to_dpp_server` give access to DTS Extensions or just checks if DPP login is correct? Because if I'm reading this correctly all correct DPP credentials will result in `DTS Extensions: Yes`. If that's correct then maybe change this echo to `DPP credentials are correct` or something similar?

2025-03-24 08:50 UTC, m-iwanicki commented on include/dts-functions.sh
> +      echo -n "DTS Extensions: "
```suggestion
      echo "Your credentials give access to:"
      echo -n "DTS Extensions: "
```

And remove `      echo "Your credentials give access to:"` couple lines below

2025-03-24 09:27 UTC, m-iwanicki requested changes

2025-03-24 09:27 UTC, m-iwanicki commented on include/dts-functions.sh
> +      check_avail_dpp_packages && install_all_dpp_packages && parse_for_premium_submenu
Move this to `if check_dts_extensions_access; then`?

2025-03-24 10:22 UTC, PLangowski commented on include/dts-functions.sh
> +      fi
e2886deb4fbc01d9e7bc97d72b6f4fed826c78a8

2025-03-24 10:23 UTC, PLangowski commented on include/dts-functions.sh
> +      echo -n "DTS Extensions: "
e2886deb4fbc01d9e7bc97d72b6f4fed826c78a8

2025-03-24 10:23 UTC, PLangowski commented on include/dts-functions.sh
> +      check_avail_dpp_packages && install_all_dpp_packages && parse_for_premium_submenu
e2886deb4fbc01d9e7bc97d72b6f4fed826c78a8

2025-03-24 10:34 UTC, PLangowski commented
@pietrushnic 
> how parsing and publishing results from HCL will work after transition to min.io

The reports will have to be downloaded from MinIO. They will not change internally, so parsing them will be the same.

2025-03-24 10:48 UTC, m-iwanicki requested changes

2025-03-24 10:48 UTC, m-iwanicki commented on include/dts-functions.sh
>          echo "NO"
```suggestion
      echo "Your credentials give access to:"
      echo -n "Dasharo Pro Package (DPP): "
      if check_for_dasharo_firmware; then
        # FIXME: what if credentials have access to
        # firmware, but check_for_dasharo_firmware will not detect any platform?
        # According to check_for_dasharo_firmware it will return 1 in both
        # cases which means that we cannot detect such case.
        print_ok "YES"
      else
        echo "NO"
```

2025-03-24 10:48 UTC, m-iwanicki commented on include/dts-functions.sh
>          echo "NO"
No need to duplicate code

2025-03-24 10:50 UTC, m-iwanicki commented on include/dts-functions.sh
> +      fi
```diff
         echo "NO"
-	      read -p "Press Enter to continue"
+       read -p "Press Enter to continue"
```

2025-03-24 11:27 UTC, PLangowski commented on include/dts-functions.sh
> +          exit 1
https://github.com/Dasharo/dts-scripts/compare/115f0b3ee9b3fcc939e3bcc8cc5d9eb75a01495f..6133ab117056246a6889e6e4bae95ac0d4b5cec6

2025-03-24 11:32 UTC, PLangowski commented on include/dts-functions.sh
>          echo "NO"
https://github.com/Dasharo/dts-scripts/compare/6133ab117056246a6889e6e4bae95ac0d4b5cec6..0dc68d406db81f868327b385c8bce94994186488

2025-03-24 11:34 UTC, m-iwanicki commented on include/dts-functions.sh
> +          exit 1
Remove redundant `exit 1` after `error_exit`

2025-03-24 11:43 UTC, PLangowski commented on include/dts-functions.sh
> +      if [ -z "$(mc alias list | grep ${DPP_EMAIL})" ]; then
d6aa898418e5656641b2c029fe8015074bcd759c

2025-03-24 13:05 UTC, PLangowski commented on reports/dasharo-hcl-report
>      if [ -a "${CMD_DASHARO_DEPLOY}" ]; then
07d1953f4d1368cf3a6ca30b1611cbd8994af94d
I removed this message, because there are several reasons why upload may fail.

2025-03-24 13:05 UTC, PLangowski commented on include/dts-functions.sh
>  download_ec() {
07d1953f4d1368cf3a6ca30b1611cbd8994af94d

2025-03-24 13:05 UTC, PLangowski commented on include/dts-functions.sh
> +   mc get "${DPP_SERVER_USER_ALIAS}/$BIOS_SIGN_LINK" "$BIOS_SIGN_FILE" > /dev/null 2>>"$ERR_LOG_FILE"
07d1953f4d1368cf3a6ca30b1611cbd8994af94d

2025-03-24 13:05 UTC, PLangowski commented on include/dts-functions.sh
> +      fi
07d1953f4d1368cf3a6ca30b1611cbd8994af94d

2025-03-25 14:46 UTC, PLangowski commented
@m-iwanicki tests passed https://github.com/Dasharo/meta-dts/actions/runs/14060224815/job/39374496694

2025-03-25 16:37 UTC, miczyg1 reviewed
Just a general comment:

I achieved uploading binaries to MinIO with just a curl (and small help of openssl to generate auth data). Maybe it would be wiser to use rather than MC, which may have to be paired with the same or at least similar version of MinIO server. This may lead to DTS eventually stop working if our server gets updated.

Downloading with curl should also be possible I believe and may be a batter solution rather than including more external executables like MC.

2025-03-28 11:07 UTC, m-iwanicki approved these changes

2025-03-31 14:51 UTC, merged